language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t babsyinks/voting-app .

script:
  - docker run babsyinks/voting-app npm run test -- --coverage

after_success:
  - docker build -t babsyinks/voting-app-client ./client
  - docker build -t babsyinks/voting-app-nginx ./nginx
  - docker build -t babsyinks/voting-app-server ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push babsyinks/voting-app-client
  - docker push babsyinks/voting-app-nginx
  - docker push babsyinks/voting-app-server

