version: '3.7'

services:
  server:
    build: .
    image: myapp-server
    container_name: myapp-node-server
    command: npm start
    volumes:
      - .:/code
      - /code/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    env_file: ./.env
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - ../../../../data:/data/db
      - ../../Desktop:/desktop
      # data-volume:/data/db
    env_file: ./.env
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./client
    image: myapp-client
    container_name: myapp-react-client
    command: npm start
    volumes:
      - ./client/:/app
      - /app/node_modules
      # mydirectory:container directory
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    node_modules:
    web-root:
      driver: local